// <auto-generated />
using System;
using GR1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GR1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250502131955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GR1.Models.LogModel", b =>
                {
                    b.Property<long>("StudentCode")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentCode", "RoomCode", "Timestamp");

                    b.HasIndex("RoomCode");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GR1.Models.RoomModel", b =>
                {
                    b.Property<int>("RoomCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomCode"));

                    b.HasKey("RoomCode");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("GR1.Models.StudentModel", b =>
                {
                    b.Property<long>("StudentCode")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentCode");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GR1.Models.LogModel", b =>
                {
                    b.HasOne("GR1.Models.RoomModel", "Room")
                        .WithMany("Logs")
                        .HasForeignKey("RoomCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GR1.Models.StudentModel", "Student")
                        .WithMany("Logs")
                        .HasForeignKey("StudentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GR1.Models.RoomModel", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("GR1.Models.StudentModel", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
